# Copyright Â©2017. The Regents of the University of California (Regents).
# All Rights Reserved. Permission to use, copy, modify, and distribute this
# software and its documentation for educational, research, and not-for-profit
# purposes, without fee and without a signed licensing agreement, is hereby
# granted, provided that the above copyright notice, this paragraph and the
# following two paragraphs appear in all copies, modifications, and
# distributions. Contact The Office of Technology Licensing, UC Berkeley, 2150
# Shattuck Avenue, Suite 510, Berkeley, CA 94720-1620, (510) 643-7201,
# otl@berkeley.edu,
# http://ipira.berkeley.edu/industry-info for commercial licensing opportunities.

# IN NO EVENT SHALL REGENTS BE LIABLE TO ANY PARTY FOR DIRECT, INDIRECT, SPECIAL,
# INCIDENTAL, OR CONSEQUENTIAL DAMAGES, INCLUDING LOST PROFITS, ARISING OUT OF
# THE USE OF THIS SOFTWARE AND ITS DOCUMENTATION, EVEN IF REGENTS HAS BEEN
# ADVISED OF THE POSSIBILITY OF SUCH DAMAGE.

# REGENTS SPECIFICALLY DISCLAIMS ANY WARRANTIES, INCLUDING, BUT NOT LIMITED TO,
# THE IMPLIED WARRANTIES OF MERCHANTABILITY AND FITNESS FOR A PARTICULAR
# PURPOSE. THE SOFTWARE AND ACCOMPANYING DOCUMENTATION, IF ANY, PROVIDED
# HEREUNDER IS PROVIDED "AS IS". REGENTS HAS NO OBLIGATION TO PROVIDE
# MAINTENANCE, SUPPORT, UPDATES, ENHANCEMENTS, OR MODIFICATIONS.
language: python

matrix:
  include:
    - name: "Python 2.7 on Xenial Linux"
      python: 2.7
      dist: xenial
      
    - name: "Python 3.5 on Xenial Linux"
      python: 3.5
      dist: xenial

    - name: "Python 3.6 on Xenial Linux"
      python: 3.6
      dist: xenial

    - name: "Python 3.7 on Xenial Linux"
      python: 3.7
      dist: xenial

    - name: "Linter"
      python: 3.7
      dist: xenial
      before_install: []
      install: []
      script:
        - pip install yapf==0.27.0  # Must use specific version.
        - pip install flake8 flake8-comprehensions flake8-quotes==2.0.0
        - ./ci/travis/format.sh --all  # Should exit with 0 for no diffs.
        - flake8

before_install:
  - sudo apt-get update
  - sudo apt-get install -y python-opengl  # For GLU.

install: 
  - pip install .

script:
  - python -c "import gqcnn"

notifications:
  email: false
